# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e3586fe9acf49d3a223092544c042d22da0b7e11bd838cf1368ccb21a0d3f1e619d3df19400b9b99782500a8a4094ff370d64a637da88297cb4c837d1ba75e

test:
  secret_key_base: 896d43fc1bc2c207a141de231f674bfa86e739af84814c4b298e06328046456465793f18ae102e55eb4955c11d8495d2150c16f1fec47174da1992faa0664f55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
